<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-04-08T09:23:36 IST" name="Default suite" finished-at="2025-04-08T09:23:41 IST" duration-ms="5469">
    <groups>
    </groups>
    <test started-at="2025-04-08T09:23:36 IST" name="Default test" finished-at="2025-04-08T09:23:41 IST" duration-ms="5469">
      <class name="MavenTestify.MavenTestify.registerTest">
        <test-method is-config="true" signature="setUp(org.testng.ITestContext)[pri:0, instance:MavenTestify.MavenTestify.registerTest@158a3b2e]" started-at="2025-04-08T09:23:36 IST" name="setUp" finished-at="2025-04-08T09:23:36 IST" duration-ms="16" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@49c675f0]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:MavenTestify.MavenTestify.registerTest@158a3b2e]" started-at="2025-04-08T09:23:36 IST" name="setUp" finished-at="2025-04-08T09:23:38 IST" duration-ms="2453" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="registerFormTest()[pri:0, instance:MavenTestify.MavenTestify.registerTest@158a3b2e]" started-at="2025-04-08T09:23:38 IST" name="registerFormTest" finished-at="2025-04-08T09:23:41 IST" duration-ms="2732" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[User already exist or due to some reason registration failed expected [https://demowebshop.tricentis.com/registerresult/1] but found [https://demowebshop.tricentis.com/register]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: User already exist or due to some reason registration failed expected [https://demowebshop.tricentis.com/registerresult/1] but found [https://demowebshop.tricentis.com/register]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at MavenTestify.MavenTestify.registerTest.registerFormTest(registerTest.java:66)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- registerFormTest -->
      </class> <!-- MavenTestify.MavenTestify.registerTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
